# Dockerfile for SRVPro Lite
FROM debian:stable-slim
FROM node:12-buster-slim

# apt
RUN apt update && apt install -y wget git \
    build-essential \
    libsqlite3-dev \
    libevent-dev \
    p7zip-full \
    python3 \
    liblua5.3-dev && \
    rm -rf /var/lib/apt/lists/*

# srvpro
COPY . /ygopro-server
WORKDIR /ygopro-server
RUN npm ci && \
    mkdir decks replays logs

# ygopro
RUN git clone --branch=server --recursive --depth=1 https://github.com/purerosefallen/ygopro && \
    cd ygopro && \
    git submodule add -f https://github.com/LordOfNightmares/expansions expansions && \
    git submodule foreach git checkout master && \
    wget -O - https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-linux.tar.gz | tar zfx - && \
    ./premake5 gmake && \
    cd build && \
    make config=release -j$(nproc) && \
    cd .. && \
    mv ./bin/release/ygopro . && \
    strip ygopro && \
    mkdir replay && \
    rm -rf .git* bin obj build ocgcore cmake lua premake* sound textures .travis.yml *.txt appveyor.yml LICENSE README.md *.lua strings.conf system.conf && \
    ls gframe | sed '/game.cpp/d' | xargs -I {} rm -rf gframe/{}

# infos
WORKDIR /ygopro-server
EXPOSE 7911 7922 7933
# VOLUME [ /ygopro-server/config, /ygopro-server/decks, /ygopro-server/replays ]

CMD [ "node", "ygopro-server.js" ]
