version: "3.7"

services:
  servpro:
    image: srvpro:dev
    build: 
      context: .
      dockerfile: Dockerfile
      # target: dev
    container_name: srvprosoloplay
    restart: always
    ports:
      - "7911:7911"
      - "7922:7922"
      - "7933:7933"